// @generated by protoc-gen-es v2.10.2 with parameter "target=ts"
// @generated from file api/v1/ai_service.proto (package memos.api.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../../google/api/annotations_pb";
import { file_google_api_field_behavior } from "../../google/api/field_behavior_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file api/v1/ai_service.proto.
 */
export const file_api_v1_ai_service: GenFile = /*@__PURE__*/
  fileDesc("ChdhcGkvdjEvYWlfc2VydmljZS5wcm90bxIMbWVtb3MuYXBpLnYxIl4KG0V4ZWN1dGVBSUluc3RydWN0aW9uUmVxdWVzdBIYCgtpbnN0cnVjdGlvbhgBIAEoCUID4EECEhkKB2NvbnRlbnQYAiABKAlCA+BBAUgAiAEBQgoKCF9jb250ZW50Ii8KHEV4ZWN1dGVBSUluc3RydWN0aW9uUmVzcG9uc2USDwoHY29udGVudBgBIAEoCTKaAQoJQUlTZXJ2aWNlEowBChRFeGVjdXRlQUlJbnN0cnVjdGlvbhIpLm1lbW9zLmFwaS52MS5FeGVjdXRlQUlJbnN0cnVjdGlvblJlcXVlc3QaKi5tZW1vcy5hcGkudjEuRXhlY3V0ZUFJSW5zdHJ1Y3Rpb25SZXNwb25zZSIdgtPkkwIXOgEqIhIvYXBpL3YxL2FpL2V4ZWN1dGVCpgEKEGNvbS5tZW1vcy5hcGkudjFCDkFpU2VydmljZVByb3RvUAFaMGdpdGh1Yi5jb20vdXNlbWVtb3MvbWVtb3MvcHJvdG8vZ2VuL2FwaS92MTthcGl2MaICA01BWKoCDE1lbW9zLkFwaS5WMcoCDE1lbW9zXEFwaVxWMeICGE1lbW9zXEFwaVxWMVxHUEJNZXRhZGF0YeoCDk1lbW9zOjpBcGk6OlYxYgZwcm90bzM", [file_google_api_annotations, file_google_api_field_behavior]);

/**
 * @generated from message memos.api.v1.ExecuteAIInstructionRequest
 */
export type ExecuteAIInstructionRequest = Message<"memos.api.v1.ExecuteAIInstructionRequest"> & {
  /**
   * Required. The instruction to send to the AI.
   *
   * @generated from field: string instruction = 1;
   */
  instruction: string;

  /**
   * Optional. The context or source text to operate on.
   *
   * @generated from field: optional string content = 2;
   */
  content?: string;
};

/**
 * Describes the message memos.api.v1.ExecuteAIInstructionRequest.
 * Use `create(ExecuteAIInstructionRequestSchema)` to create a new message.
 */
export const ExecuteAIInstructionRequestSchema: GenMessage<ExecuteAIInstructionRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_ai_service, 0);

/**
 * @generated from message memos.api.v1.ExecuteAIInstructionResponse
 */
export type ExecuteAIInstructionResponse = Message<"memos.api.v1.ExecuteAIInstructionResponse"> & {
  /**
   * The result of the AI instruction execution.
   *
   * @generated from field: string content = 1;
   */
  content: string;
};

/**
 * Describes the message memos.api.v1.ExecuteAIInstructionResponse.
 * Use `create(ExecuteAIInstructionResponseSchema)` to create a new message.
 */
export const ExecuteAIInstructionResponseSchema: GenMessage<ExecuteAIInstructionResponse> = /*@__PURE__*/
  messageDesc(file_api_v1_ai_service, 1);

/**
 * @generated from service memos.api.v1.AIService
 */
export const AIService: GenService<{
  /**
   * ExecuteAIInstruction executes an AI instruction on a memo or free-form text.
   *
   * @generated from rpc memos.api.v1.AIService.ExecuteAIInstruction
   */
  executeAIInstruction: {
    methodKind: "unary";
    input: typeof ExecuteAIInstructionRequestSchema;
    output: typeof ExecuteAIInstructionResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_api_v1_ai_service, 0);

